name: Deploy TicTacToe Farcaster
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          VITE_NEYNAR_API_KEY: ${{ secrets.VITE_NEYNAR_API_KEY }}
          VITE_NEYNAR_SIGNER_UUID: ${{ secrets.VITE_NEYNAR_SIGNER_UUID }}
          VITE_FARCASTER_MOCK: 'false'
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tictactoe-farcaster
          directory: dist
