[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_FARCASTER_MOCK = "false"

[context.deploy-preview.environment]
  VITE_FARCASTER_MOCK = "true"

[context.branch-deploy.environment]
  VITE_FARCASTER_MOCK = "true"
